package ma.onda.rag;

import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.context.annotation.Bean;
import org.testcontainers.postgresql.PostgreSQLContainer;
import org.testcontainers.utility.DockerImageName;

@TestConfiguration(proxyBeanMethods = false)
class TestcontainersConfiguration {

    /**
     * pgvector container used by the full-context smoke test. The schema is
     * generated by Hibernate ({@code ddl-auto: create-drop} is set on the
     * test) and Spring AI creates the {@code vector_store} table, so no
     * init script is required here.
     */
    @Bean
    @ServiceConnection
    PostgreSQLContainer pgvectorContainer() {
        return new PostgreSQLContainer(DockerImageName.parse("pgvector/pgvector:pg17"));
    }
}
